kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: llm
nodes:
  - role: control-plane
  - role: worker
    extraPortMappings:
      - containerPort: 11434
        hostPort: 11434
        listenAddress: "0.0.0.0"
        protocol: TCP
